<template>
  <ion-page>
    <ion-content :fullscreen="true">
      <div class="logo">
        <video loop autoplay muted>
          <source src="assets/img/BUMPER FANATICOS.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        <div class="loadingio-spinner-ripple-knrbu6mhhy" v-if="loaded">
          <div class="ldio-algezokiaa6">
            <div></div>
            <div></div>
          </div>
        </div>
        <br />
        <button class="btniniciar" v-if="loaded1" @click="tab1()">iniciar</button>
      </div>
    </ion-content>
  </ion-page>
</template>

<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Ubuntu&display=swap");
ion-toolbar {
  text-align: center;
  color: white;
  --background: #02796f;
}
ion-content {
  --background: black;
}
ion-card {
  margin-top: 1%;
  margin-left: 30px;
  margin-right: 30px;
  --color: "warning";
}
.logo {
  text-align: center;
  margin-top: 40%;
}
video {
  width: 100%;
  height: auto;
}

@keyframes ldio-algezokiaa6 {
  0% {
    top: 98px;
    left: 98px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 19px;
    left: 19px;
    width: 158px;
    height: 158px;
    opacity: 0;
  }
}

.ldio-algezokiaa6 div {
  position: absolute;
  border-width: 2px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-algezokiaa6 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}

.ldio-algezokiaa6 div:nth-child(1) {
  border-color: #93dbe9;
}

.ldio-algezokiaa6 div:nth-child(2) {
  border-color: #689cc5;
  animation-delay: -0.5s;
}

.loadingio-spinner-ripple-knrbu6mhhy {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #000000;
}
.ldio-algezokiaa6 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-algezokiaa6 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */

.btniniciar {
  -webkit-border-radius: 20px;
  -moz-border-radius: 20px;
  border-radius: 20px;
  color: #ffffff;
  font-family: "Ubuntu", sans-serif;
  font-size: 22px;
  font-weight: 500;
  padding: 19px;
  background-color: #526172;
  -webkit-box-shadow: 1px 1px 20px 0 #000000;
  -moz-box-shadow: 1px 1px 20px 0 #000000;
  box-shadow: 1px 1px 20px 0 #000000;
  text-shadow: 1px 1px 20px #000000;
  border: solid #526172 1px;
  text-decoration: none;
  display: inline-block;
  cursor: pointer;
  text-align: center;
}

.btniniciar:hover {
  background: #526172;
  border: solid #526172 1px;
  -webkit-border-radius: 20px;
  -moz-border-radius: 20px;
  border-radius: 20px;
  text-decoration: none;
}
</style>

<script>
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  alertController,
} from "@ionic/vue";
import { defineComponent } from "vue";

class Data {
  constructor(
    /* Usuarios */
    user,
    password,
    username,
    userlastname,
    usercountry,
    usercity,
    useralias,
    userscore,
    userexp,

    /* Trivia */
    main,
    type,
    code,
    quest,
    answer,
    rate
  ) {
    /* Usuarios */
    this.user = user;
    this.password = password;
    this.username = username;
    this.userlastname = userlastname;
    this.usercountry = usercountry;
    this.usercity = usercity;
    this.useralias = useralias;
    this.userscore = userscore;
    this.userexp = userexp;

    /* Trivia */
    this.main = main;
    this.type = type;
    this.code = code;
    this.quest = quest;
    this.answer = answer;
    this.rate = rate;
  }
}

export default {
  components: {
    IonPage,
    IonContent,
  },
  data() {
    return {
      data: new Data(),
      datos: [],
      test: "ok",
      isConnected: false,
      name: "",
      email: "",
      /* cheks */
      loaded: true,
      loaded1: false,
      versioninterna: 5,
    };
  },
  name: "Tabs",

  created() {
    this.load();
  },
  methods: {
    load() {
      fetch("https://fanaticos.herokuapp.com/api", { method: "GET" })
        .then((res) => res.json())
        .then((data) => {
          this.datos = data;
          this.loaded = false;
          this.fnversion();
        })
        .catch((err)=> this.chkinternetconnection());
        
    },
    fnversion(){
      let version = 0;
      for (let i = 0; i < this.datos.length; i++) {
        const element = this.datos[i];
        if (element.version > 0){
          version = element.version;
        }
      }
      if (version != this.versioninterna){
        this.loaded = true;
        this.loaded1 = false;
        this.presentAlert("Atención","Version antigua","Por favor descarga la ultima versión del juego. Si este mensaje persiste, desintala e intala nuevamente. Gracias.")
      } else {
        this.$router.push('/tab1');
      }
    },
    tab1(){
      this.$router.push('/tab1');
    },
    chkinternetconnection(){
      if (this.datos.length <= 0){
        this.presentAlert("Error de red","","Debes conectarte a internet para jugar.");
        this.loaded = true;
        this.loaded1 = false;
      }
    },
    async presentAlert(header, subheader,message) {
      const alert = await alertController.create({
        cssClass: "my-custom-class",
        header: header,
        subHeader: subheader,
        message: message,
        buttons: ["OK"],
      });
      return alert.present();
    },
  },

  computed: {},
};
</script>